framework:
  container_name: oh-framework
  image: daocloud.io/oh-framework
  working_dir: /data
  ports:
    - "8080:8080"
  environment:
   SERVER_PORT: 8080
   SPRING_DATASOURCE_DRUID_URL: "jdbc:mysql:/127.0.0.0:3306/oh?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false"
   SPRING_DATASOURCE_DRUID_USERNAME: "root"
   SPRING_DATASOURCE_DRUID_PASSWORD: "root"
   SERVER_CONTEXT_PATH: "/"
   SPRING_DEVTOOLS_RESTART_ENABLED: "false"
  volumes:
      - ./data:/data
  restart: always